-- Oracle APEX Event Management Portal Schema

-- cleanup
BEGIN
    FOR c IN (SELECT table_name FROM user_tables WHERE table_name IN ('PARTICIPANTS', 'EVENTS', 'SCHEDULES', 'REGISTRATIONS', 'CERTIFICATES')) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || c.table_name || ' CASCADE CONSTRAINTS';
    END LOOP;
END;
/

-- 1. Participants Table
CREATE TABLE participants (
    participant_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name           VARCHAR2(100) NOT NULL,
    email          VARCHAR2(100) NOT NULL UNIQUE,
    phone          VARCHAR2(20),
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Events Table
CREATE TABLE events (
    event_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    title          VARCHAR2(200) NOT NULL,
    description    VARCHAR2(4000),
    start_date     DATE NOT NULL,
    end_date       DATE NOT NULL,
    location       VARCHAR2(200),
    max_attendees  NUMBER,
    status         VARCHAR2(20) DEFAULT 'UPCOMING' CHECK (status IN ('UPCOMING', 'ONGOING', 'COMPLETED', 'CANCELLED')),
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. Schedules Table (Sessions within an event)
CREATE TABLE schedules (
    schedule_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    event_id       NUMBER REFERENCES events(event_id) ON DELETE CASCADE,
    session_title  VARCHAR2(200) NOT NULL,
    speaker        VARCHAR2(100),
    start_time     TIMESTAMP NOT NULL,
    end_time       TIMESTAMP NOT NULL,
    room_link      VARCHAR2(500) -- Physical room or Meeting Link
);

-- 4. Registrations Table
CREATE TABLE registrations (
    registration_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    event_id        NUMBER REFERENCES events(event_id) ON DELETE CASCADE,
    participant_id  NUMBER REFERENCES participants(participant_id) ON DELETE CASCADE,
    registered_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status          VARCHAR2(20) DEFAULT 'CONFIRMED' CHECK (status IN ('CONFIRMED', 'CANCELLED', 'ATTENDED')),
    CONSTRAINT unique_registration UNIQUE (event_id, participant_id)
);

-- 5. Certificates Table
CREATE TABLE certificates (
    certificate_id  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    registration_id NUMBER REFERENCES registrations(registration_id) ON DELETE CASCADE,
    certificate_uuid VARCHAR2(64) DEFAULT SYS_GUID() NOT NULL UNIQUE, -- For verification
    issued_date     DATE DEFAULT SYSDATE,
    pdf_blob        BLOB, -- Store generated PDF if needed, or generate on fly
    mime_type       VARCHAR2(50) DEFAULT 'application/pdf'
);
